# 触发 workflow 的事件
name: test
on:
  [push]
# 一个workflow由执行的一项或多项job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:
          sudo apt update&&
          sudo apt install qemu-user-static -y&&
          sudo apt install qemu-user-binfmt -y&&
          update-binfmts --display
      - run:
          sudo apt install debootstrap -y&&
          sudo qemu-debootstrap --arch armel stable ~/armel-chroot
          sudo cp /usr/bin/qemu-arm-static ~/armel-chroot/usr/bin/qemu-arm-static&&
          sudo chroot ~/armel-chroot qemu-arm-static /bin/bash&&
          uname -m