# 触发 workflow 的事件
name: test
on:
  [push]
# 一个workflow由执行的一项或多项job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:
          sudo apt update\
          sudo apt install qemu-user-static -y\
          sudo apt install qemu-user-binfmt -y