# 触发 workflow 的事件
name: test
on:
  [push]
# 一个workflow由执行的一项或多项job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          commands: |
            uname -a